use rand::prelude::*;
use std::{
    sync::atomic::{AtomicU64, Ordering},
    thread,
    time::Duration,
};

fn get_key() -> u64 {
    static KEY: AtomicU64 = AtomicU64::new(0);
    let key = KEY.load(Ordering::Relaxed);
    let mut rn = rand::rng();
    if key == 0 {
        let new_key: u64 = rn.random();

        thread::sleep(Duration::from_millis(rn.random_range(0..20)));
        match KEY.compare_exchange(0, new_key, Ordering::Relaxed, Ordering::Relaxed) {
            Ok(_) => {
                println!("This thread won the data race!");
                new_key
            }
            Err(k) => k, // we lost the data race and return a key generated by some other thread
        }
    } else {
        key
    }
}

fn main() {
    let mut handles = vec![];

    for i in 0..20 {
        handles.push(thread::spawn(move || {
            println!("thread {:02} has key {}", i, get_key())
        }));
    }

    for handle in handles {
        handle.join().unwrap();
    }
}
